#!/usr/bin/env bash
# CPT AI — One-command setup
# Usage: ./setup/setup.sh
set -euo pipefail

# setup.sh lives in setup/ — project root is one level up
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="$HOME/ai-mcp-env"
MCP_CONFIG="$HOME/opensearch_mcp_config.yml"
ENV_FILE="$REPO_DIR/.env"
CURRENT_USER="$(whoami)"

# --- Colors ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

banner() { echo -e "\n${CYAN}══════════════════════════════════════════${NC}"; echo -e "${CYAN}  $1${NC}"; echo -e "${CYAN}══════════════════════════════════════════${NC}\n"; }
info()   { echo -e "${GREEN}✓${NC} $1"; }
warn()   { echo -e "${YELLOW}!${NC} $1"; }
err()    { echo -e "${RED}✗${NC} $1"; }
ask()    { read -rp "$(echo -e "${YELLOW}?${NC} $1: ")" "$2"; }
ask_secret() { read -srp "$(echo -e "${YELLOW}?${NC} $1: ")" "$2"; echo; }

# ── Pre-flight checks ─────────────────────────────────────────────
banner "CPT AI Setup — Pre-flight Checks"

PREFLIGHT_OK=true

# Python 3
if command -v python3 &>/dev/null; then
    PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
    PY_MAJOR=$(python3 -c 'import sys; print(sys.version_info.major)')
    PY_MINOR=$(python3 -c 'import sys; print(sys.version_info.minor)')
    if [[ "$PY_MAJOR" -ge 3 && "$PY_MINOR" -ge 12 ]]; then
        info "Python $PY_VER"
    else
        err "Python $PY_VER found — 3.12+ required"
        PREFLIGHT_OK=false
    fi
else
    err "python3 not found — install Python 3.12+"
    PREFLIGHT_OK=false
fi

# pip
if python3 -m pip --version &>/dev/null 2>&1; then
    info "pip available"
else
    err "pip not found — install python3-pip"
    PREFLIGHT_OK=false
fi

# git
if command -v git &>/dev/null; then
    info "git $(git --version | awk '{print $3}')"
else
    warn "git not found — not required for setup, but needed to pull updates"
fi

# sudo
if sudo -n true 2>/dev/null; then
    info "sudo access (passwordless)"
elif sudo -v 2>/dev/null; then
    info "sudo access (password may be required)"
else
    err "sudo access required — needed to install systemd services"
    PREFLIGHT_OK=false
fi

# systemctl
if command -v systemctl &>/dev/null; then
    info "systemd available"
else
    err "systemctl not found — systemd is required"
    PREFLIGHT_OK=false
fi

# Network (basic check)
if ping -c 1 -W 3 pypi.org &>/dev/null 2>&1; then
    info "Network connectivity (pypi.org reachable)"
else
    warn "Cannot reach pypi.org — pip install may fail without network"
fi

info "User: $CURRENT_USER"
info "Repo: $REPO_DIR"

if ! $PREFLIGHT_OK; then
    echo ""
    err "Pre-flight checks failed. Fix the issues above and re-run ./setup/setup.sh"
    exit 1
fi

echo ""
info "All pre-flight checks passed!"

# ── Collect credentials ───────────────────────────────────────────
banner "OpenSearch Configuration"

ask "OpenSearch host (e.g. opensearch.example.com)" OS_HOST
ask "OpenSearch port [443]" OS_PORT
OS_PORT=${OS_PORT:-443}
ask "OpenSearch username" OS_USER
ask_secret "OpenSearch password" OS_PASS

banner "AI Model Configuration"

echo "  1) Google Gemini (gemini-2.0-flash)"
echo "  2) Red Hat Granite (granite-3-3-8b-instruct)"
echo ""
read -rp "$(echo -e "${YELLOW}?${NC} Choose AI model [1]: ")" MODEL_CHOICE
MODEL_CHOICE=${MODEL_CHOICE:-1}

if [[ "$MODEL_CHOICE" == "2" ]]; then
    MODEL_NAME="granite-3-3-8b-instruct"
    ask "Granite endpoint URL" MODEL_ENDPOINT
    ask_secret "Granite API key" MODEL_KEY
else
    MODEL_NAME="gemini-2.0-flash"
    MODEL_ENDPOINT="https://generativelanguage.googleapis.com/v1beta/openai"
    ask_secret "Gemini API key" MODEL_KEY
fi

# ── Create virtual environment ────────────────────────────────────
banner "Creating Virtual Environment"

if [[ -d "$VENV_DIR" ]]; then
    warn "Virtual environment already exists at $VENV_DIR — reusing it"
else
    python3 -m venv "$VENV_DIR"
    info "Created virtual environment at $VENV_DIR"
fi

source "$VENV_DIR/bin/activate"
pip install --upgrade pip -q
info "Upgraded pip"

# ── Install dependencies ──────────────────────────────────────────
banner "Installing Dependencies"

pip install -r "$REPO_DIR/requirements.txt" -q
info "Installed core + API + CLI dependencies"

pip install -r "$REPO_DIR/components/dashboard/requirements.txt" -q
info "Installed dashboard dependencies"

# ── Write .env ────────────────────────────────────────────────────
banner "Writing Configuration"

cat > "$ENV_FILE" <<EOF
# CPT AI Configuration — generated by setup.sh

# --- MCP Server ---
MCP_URL=http://localhost:9900/sse
OPENSEARCH_CLUSTER=zathras
OPENSEARCH_INDEX=zathras-results

# --- OpenSearch ---
OPENSEARCH_HOST=$OS_HOST
OPENSEARCH_PORT=$OS_PORT
OPENSEARCH_USERNAME=$OS_USER
OPENSEARCH_PASSWORD=$OS_PASS

# --- AI Model ---
MODEL_NAME=$MODEL_NAME
MODELS_CORP_API_KEY=$MODEL_KEY
MODELS_CORP_ENDPOINT=$MODEL_ENDPOINT

# --- SSL ---
SSL_VERIFY=false
EOF

info "Wrote $ENV_FILE"

# ── Write MCP config ─────────────────────────────────────────────
cat > "$MCP_CONFIG" <<EOF
clusters:
  zathras:
    opensearch_url: "https://$OS_HOST:$OS_PORT"
    opensearch_username: "$OS_USER"
    opensearch_password: "$OS_PASS"
    max_response_size: 5242880
EOF

info "Wrote $MCP_CONFIG"

# ── Install systemd services ─────────────────────────────────────
banner "Installing Systemd Services"

SYSTEMD_SRC="$SCRIPT_DIR/systemd"
SERVICES=(cpt-ai-mcp cpt-ai-api cpt-ai-dashboard cpt-ai-regression)

for svc in "${SERVICES[@]}"; do
    # Replace placeholders with actual paths for this machine/user
    sed \
        -e "s|__USER__|$CURRENT_USER|g" \
        -e "s|__REPO_DIR__|$REPO_DIR|g" \
        -e "s|__VENV_DIR__|$VENV_DIR|g" \
        -e "s|__HOME__|$HOME|g" \
        "$SYSTEMD_SRC/${svc}.service" \
        | sudo tee "/etc/systemd/system/${svc}.service" >/dev/null
done

sudo systemctl daemon-reload
info "Installed and patched unit files for user=$CURRENT_USER"

# Start MCP first (others depend on it), then the rest
for svc in "${SERVICES[@]}"; do
    sudo systemctl enable "$svc" --now 2>/dev/null || true
    info "Enabled and started $svc"
done

# ── Verify ────────────────────────────────────────────────────────
banner "Verifying Services"

sleep 3
ALL_OK=true
for svc in "${SERVICES[@]}"; do
    if sudo systemctl is-active --quiet "$svc"; then
        info "$svc is running"
    else
        err "$svc failed to start — check: sudo journalctl -u $svc -n 20"
        ALL_OK=false
    fi
done

# ── Done ──────────────────────────────────────────────────────────
if $ALL_OK; then
    banner "Setup Complete!"
else
    banner "Setup Complete (with warnings)"
fi

echo -e "  ${GREEN}MCP Server${NC}   http://localhost:9900"
echo -e "  ${GREEN}API${NC}          http://localhost:8000      (Swagger: /docs)"
echo -e "  ${GREEN}Dashboard${NC}    http://localhost:8050"
echo -e "  ${GREEN}Regression${NC}   http://localhost:8060"
echo ""
echo -e "  ${CYAN}CLI usage:${NC}"
echo -e "    source ~/ai-mcp-env/bin/activate"
echo -e "    cd $REPO_DIR"
echo -e "    python3 components/cli/json/regression_analyzer.py"
echo -e "    python3 components/cli/csv/csv_regression_analyzer.py --csv file1.csv file2.csv"
echo ""
echo -e "  ${CYAN}Service management:${NC}"
echo -e "    sudo systemctl status cpt-ai-api"
echo -e "    sudo systemctl restart cpt-ai-api"
echo -e "    sudo journalctl -u cpt-ai-api -f"
echo ""
echo -e "  ${CYAN}Stop everything:${NC}"
echo -e "    sudo systemctl stop cpt-ai-mcp cpt-ai-api cpt-ai-dashboard cpt-ai-regression"
echo ""
